### ISSUE TITLE
[doc] 6.9.4.4  Monitor Custom Secret Certificates - glob specification unclear

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#1006]
6.9.4.4  Monitor Custom Secret Certificates:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_monitor_custom_secret_certificates

-----------------------

Tried to configure monitoring for custom certificates and tried this in the values.yaml:

     includeKeys:
        - "{ca.crt,tls.crt}"

--> but this did not work as the glob did not match

had to specify something like this:

      includeKeys:
        - "*.crt"

--> could we add an example on how to monitor ALL certificates in secrets?

**Comment by Martin-Weiss** [comment]
FYI - this is how I configured it to monitor ALL secrets in all namespaces that have a .pem and .crt!

```
customSecret:
  enabled: true

  certs:
    # Name of the custom secret to create the Deployment resource.
    # If you have multiple custom secret to monitoring, copy the below
    # section and differs in name
    - name: custom-secrets
      # Kubernetes namespace to list secrets (optional).
      namespace: []
      # Secret globs to include when looking for secret data keys (optional).
      includeKeys:
        - "*.crt"
        - "*.pem"
      # Secret globs to exclude when looking for secret data keys (optional).
      excludeKeys: []
      # Label selector to find secrets to publish as metrics (optional).
      # Annotation selector to find secrets to publish as metrics (optional).
      # If both labelSelector and annotationSelector configured, the cert-exporter
      # search secrets with AND operation, which means the secrets are the intersects
      # of labelSelector and annotationSelector.
      labelSelector: []
      annotationSelector: []
      nodeSelector: {}
      affinity: {}

```

**Comment by r0ckarong** [comment]
> --> could we add an example on how to monitor ALL certificates in secrets?

@innobead Can you help with this?

**Comment by jenting** [comment]
cc me

**Comment by jenting** [comment]
> 6.9.4.4 Monitor Custom Secret Certificates:
> 
> https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_monitor_custom_secret_certificates
> 
> Tried to configure monitoring for custom certificates and tried this in the values.yaml:
> 
> ```
>  includeKeys:
>     - "{ca.crt,tls.crt}"
> ```
> 
> --> but this did not work as the glob did not match

I remember I had test it before, could you please provide the cert-exporter pod log to me? thanks.

> 
> had to specify something like this:
> 
> ```
>   includeKeys:
>     - "*.crt"
> ```
> 
> --> could we add an example on how to monitor ALL certificates in secrets?

ok

**Comment by Martin-Weiss** [comment]
This works for me:

```
customSecret:
  enabled: true

  certs:
    # Name of the custom secret to create the Deployment resource.
    # If you have multiple custom secret to monitoring, copy the below
    # section and differs in name
    - name: custom-secrets
      # Kubernetes namespace to list secrets (optional).
      namespace: []
      # Secret globs to include when looking for secret data keys (optional).
      includeKeys:
        - "*.crt"
        - "*.pem"
      #  - "{ca.crt,tls.crt}"
      # Secret globs to exclude when looking for secret data keys (optional).
      excludeKeys: []
      # Label selector to find secrets to publish as metrics (optional).
      # Annotation selector to find secrets to publish as metrics (optional).
      # If both labelSelector and annotationSelector configured, the cert-exporter
      # search secrets with AND operation, which means the secrets are the intersects
      # of labelSelector and annotationSelector.
      labelSelector: []
      annotationSelector: []
      nodeSelector: {}
      affinity: {}
```
And when I use this it does not work:

```
customSecret:
  enabled: true

  certs:
    # Name of the custom secret to create the Deployment resource.
    # If you have multiple custom secret to monitoring, copy the below
    # section and differs in name
    - name: custom-secrets
      # Kubernetes namespace to list secrets (optional).
      namespace: []
      # Secret globs to include when looking for secret data keys (optional).
      includeKeys:
              #  - "*.crt"
              #  - "*.pem"
       - "{ca.crt,tls.crt}"
      # Secret globs to exclude when looking for secret data keys (optional).
      excludeKeys: []
      # Label selector to find secrets to publish as metrics (optional).
      # Annotation selector to find secrets to publish as metrics (optional).
      # If both labelSelector and annotationSelector configured, the cert-exporter
      # search secrets with AND operation, which means the secrets are the intersects
      # of labelSelector and annotationSelector.
      labelSelector: []
      annotationSelector: []
      nodeSelector: {}
      affinity: {}

```

And here are the relevant logs:

```
I0929 07:27:04.781301       1 periodicSecretChecker.go:89] Reviewing secret monitoring-tls in monitoring
I0929 07:27:04.781303       1 periodicSecretChecker.go:106] Annotations matched. Parsing Secret.
I0929 07:27:04.781306       1 periodicSecretChecker.go:145] Ignoring tls.key. Does not match [{ca.crt,tls.crt}] or matches [].
I0929 07:27:04.781310       1 periodicSecretChecker.go:145] Ignoring tls.crt. Does not match [{ca.crt,tls.crt}] or matches [].
```
