### ISSUE TITLE
[doc] TLS should be disabled in air-gapped docker registry config.yml

### ISSUE THREAD

**Issue by kraml** [SUSE/doc-caasp#685]
The doc setup nginx as a reverse proxy in front of docker registry in the air-gapped environment.

Since nginx talks to the upstream server in http(no s), the registry should disable TLS support or else nginx will not be able to properly communicate with it.

The current code snippet in nginx configure example in the doc:

```
upstream docker-registry {
    server 127.0.0.1:5000;
}

location /v2/ {
    proxy_pass http://docker-registry;
}
```

The docker registry config.yml:

```
http:
  tls:
    certificate: /etc/rmt/ssl/rmt-server.crt
    key: /etc/rmt/ssl/rmt-server.key
```
The tls node needs to be removed. It's only needed if the registry is facing the outside without nginx as a reversed proxy.

https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-deployment/#id-1.6.2.11.3.7
