### ISSUE TITLE
[doc] 4.8.1.2  Deploy ingress controller from helm chart - number of replicas

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#834]
4.8.1.2  Deploy ingress controller from helm chart

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_deploy_ingress_controller_from_helm_chart

------
I believe we should also recommend to have at least replica=2 for both PODs

**Comment by r0ckarong** [comment]
@lcavajani Would this have to be specified as a parameter to helm during installation or as a config change later on?

**Comment by lcavajani** [comment]
@r0ckarong this has to be specified in the `nginx-ingress-config-values.yaml`

If we take the example from the doc, this would look like:

```
# Enable the creation of pod security policy
podSecurityPolicy:
  enabled: false

# Create a specific service account
serviceAccount:
  create: true
  name: nginx-ingress

controller:
  # Number of controller pods
  replicaCount: 3
```
