### ISSUE TITLE
[doc] 9.1.2  Creating an etcd Cluster Database Backup

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-caasp#863]
9.1.2  Creating an etcd Cluster Database Backup:

https://susedoc.github.io/doc-caasp/master/single-html/caasp-admin/#_creating_an_etcd_cluster_database_backup

-----

Add a better example with remote NFS export and correct etcd image..

--> using "hostpath" and writing local on a master that gets lost and not even backed up is not the best way.. so I would recommend NFS or cephFS - either direct - see below - or maybe also with a PV/PVC..

Just as example I am using this:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-backup
  namespace: kube-system
  labels:
    jobgroup: backup
spec:
  template:
    metadata:
      name: etcd-backup
      labels:
        jobgroup: backup
    spec:
      containers:
      - name: etcd-backup
        image: registry.suse.com/caasp/v4/etcd:3.4.3
        env:
        - name: ETCDCTL_API
          value: "3"
        command: ["/bin/sh"]
        args: ["-c", "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key snapshot save /backup/etcd-snapshot-$(date +%Y-%m-%d_%H:%M:%S_%Z).db"]
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: etcd-certs
          readOnly: true
        - mountPath: /backup
          name: etcd-backup
      restartPolicy: OnFailure
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        operator: Exists
      hostNetwork: true
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/kubernetes/pki/etcd
          type: DirectoryOrCreate
      - name: etcd-backup
        nfs:
          server: caasp4-01.suse
          path: /exports/caasp4-cluster/etcd-backup
```
